apiVersion: v1
kind: Service
metadata:
  name: drupal10-svc
spec:
  type: ClusterIP
  selector:
    app: drupal10     # This must match your Deployment's label
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
