apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal10-code-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /opt/d10deploy/web  # ✅ Adjusted to correct web root
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal10-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
