apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: school-two-drupal-tls
  namespace: default
spec:
  secretName: school-two-drupal-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
    - school-two.nsgtech.eu
